redis:
  host: 192.168.58.134
  port: 6379
  pool:
    max-active: 8
    max-wait: 1
    max-idle: 8
    min-idle: 0
  timeout: 0

spring:
  data:
    mongodb:
      uri: mongodb://60.205.176.135:27017/zhou
